version: "3.9"

services:
  # back:
  #   build:
  #     context: ./back
  #   container_name: nest-backend
  #   ports:
  #     - "3001:3001"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./back:/app
  #     - /app/node_modules
  #   command: npm run start:dev

  # front:
  #   build:
  #     context: ./front
  #   container_name: react-frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./front:/app
  #     - /app/node_modules
  #   command: npm run start
  #   depends_on:
  #     - back

  db:
    image: postgres:16
    container_name: nest-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: nest-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
